### PR TITLE
Initial documentation

### LINKED ISSUE #30: Create initial documentation

### PR DESCRIPTION
**Pull request by IljaN**
Initial docs structure.

Related to #30

### CODE REVIEW

**Comment by IljaN** [comment]
@xoxys Are further changes required to drone.yml to deploy website correctly?

**Comment by xoxys** [comment]
@IljaN sure :) First you need an empty (!) docs branch (https://stackoverflow.com/a/34100189). Make sure to name it `docs`. For the drone changes have a look at:
https://github.com/owncloud/ocis-accounts/pull/6/files#diff-74dc60589e0610c07e491b31f8693b2b (drone)
https://github.com/owncloud/ocis-accounts/pull/6/files#diff-b67911656ef5d18c4ae36cb6741b7965 (makefile)
https://github.com/owncloud/ocis-accounts/pull/8/files (multiple small fixes)

**Comment by micbar** [comment]
@IljaN I can push a commit with the fixes to the branch.

**Review by micbar — APPROVED** [review]
LGTM

**Pull request merged**
