### PR TITLE
Use konnectd-upstream v0.30.0

### PR DESCRIPTION
**Pull request by IljaN**
Issue: https://github.com/owncloud/product/issues/14

### CODE REVIEW

**Review by C0rby — APPROVED** [review]
Nice :+1:

**Review by C0rby — CHANGES_REQUESTED** [review]
Oh the ci build failed

**Comment by C0rby** [comment]
> Oh the ci build failed

@IljaN, I fixed it. (I hope). CI is green again. So from my POV it's good to merge.

**Review by C0rby — APPROVED** [review]
:+1:

**Review by refs — APPROVED** [review]

**Pull request merged**
