### PR TITLE
Adding more clients: graph explorer, desktop, ios and android

### LINKED ISSUE #19: Add mobile/desktop clients to identifier-configuration
ownCloud mobile and desktop clients need to be added here:

https://github.com/owncloud/ocis-konnectd/blob/6543854f42a49b9124e113c5d1f3e57a593b92e5/assets/identifier-registration.yaml

@deepdiver can you please provide the required params or PR?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #19

### CODE REVIEW

**Comment by IljaN** [comment]
Please run go:generate go run github.com/UnnoTed/fileb0x embed.yml additionally to bake the config file in to the binary.

**Review by IljaN — CHANGES_REQUESTED** [review]
Please run ```go:generate go run github.com/UnnoTed/fileb0x embed.yml``` additionally to bake the config file in to the binary.

**Comment by DeepDiver1975** [comment]
> Please run `go:generate go run github.com/UnnoTed/fileb0x embed.yml` additionally to bake the config file in to the binary.

done - thx

**Review by IljaN — APPROVED** [review]

**Comment by IljaN** [comment]
Thanks!

**Pull request merged**
