### PR TITLE
Basic span definitions

### PR DESCRIPTION
**Pull request by refs**
# What?

This PR aims to create basic spans within the `ocis-konnectd` service. @IljaN is there a way to have tracing inside the konnectd lib? It doulw be nice to have some eyes inside, and not just load the routes.

### CODE REVIEW

**Review by IljaN — APPROVED** [review]

**Comment by IljaN** [comment]
> is there a way to have tracing inside the konnectd lib? It be nice to have some eyes inside, and not just load the routes. 

What kind of api is required to instrument the lib?

**Comment by refs** [comment]
> > is there a way to have tracing inside the konnectd lib? It be nice to have some eyes inside, and not just load the routes.
> 
> What kind of api is required to instrument the lib?

opencensus

**Comment by IljaN** [comment]
> opencensus

I rather mean at a code level. You have access to all the handlers here:
https://github.com/owncloud/ocis-konnectd/blob/master/pkg/service/v0/service.go#L59

Is it enough to wrap them?

Mux is built here: https://github.com/owncloud/ocis-konnectd/blob/master/pkg/service/v0/service.go#L172

They have no tracing capabilities inside their project so this probably would need upstream work unless we can somehow work with the above primitives.

**Comment by refs** [comment]
I think having telemetry upstream would benefit both parties 🤔. We can catch up tomorrow

**Pull request merged**
