### PR TITLE
Tracing Middleware

### PR DESCRIPTION
**Pull request by refs**
Start the service:

```console
KONNECTD_TLS=false \
go run cmd/ocis-konnectd/main.go server \
--tracing-enabled \
--tracing-type jaeger \
--tracing-collector http://localhost:14268/api/traces
```

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/tracing.go  -1
+ pkg/server/http/server.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5145940&bid=16902174)

**Review by butonic — APPROVED** [review]

**Comment by refs** [comment]
@micbar is codacy 💀 ?

**Comment by micbar** [comment]
> @micbar is codacy 💀 ?

Seems so. The Result is on the Codacy site.
Seems like it didnt get back to GH.

Can you force push?

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/tracing.go  -1
+ pkg/server/http/server.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5145940&bid=16902174)

**Pull request merged**
